name: "Changelog"
description: "A log of all the changes made in an update"
title: "Skyfall Update vX.Y.Z"
labels: ["type: documentation"]
assignees: ["McSnurtle"]
projects: ["McSnurtle/1"]

body:
  - type: textarea
    id: name
    attributes:
      label: "Changelog"
      value: |
        # *"\[Name\]" Update*<br>

        All notable changes to this project from this update will be documented in this file.

        The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/),
        and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
        
        **Download here:** [vX.Y.Z](<https://github.com/McSnurtle/Project-Skyfall/releases/tag/vX.Y.Z>)

        *A comprehensive list of mod changes can be found [here](<https://github.com/McSnurtle/Project-Skyfall/compare/vA.B.C...vX.Y.Z>)
  - type: textarea
    id: preview
    attributes:
      label: "Update Preview :eyes:"
      description: "A sneak preview of what's new in this update."
      value: " - "
    validations:
      required: true
  - type: textarea
    id: additions
    attributes:
      label: "Added"
      description: "Additions to the modpack and / or server since the previous update."
      value: |
        - 
    validations:
      required: true
  - type: textarea
    id: changes
    attributes:
      label: "Changed"
      description: "Changes to the modpack and / or server since the previous update."
      value: |
        - 
    validations:
      required: false
  - type: textarea
    id: removals
    attributes:
      label: "Removed"
      description: "Removals to the modpack and / or server since the previous update."
      value: |
        - 
    validations:
      required: false
  - type: textarea
    id: fixes
    attributes:
      label: "Fixed"
      description: "Bugs that were fixed in this update."
      value: |
        - 
    validations:
      required: false
  - type: textarea
    id: issues
    attributes:
      label: "Known Issues"
      description: "Known problems with this update"
      value: " - "
    validations:
      required: false
