name: Bug report
description: Report a bug or problem with the server
title: "[Bug] Flipping around"
labels: ["bug", "unknown"]
projects: ["McSnurtle/1"]
assignees:
  - McSnurtle
body:
  - type: markdown
    id: warning
    attributes:
      label: |
        **Before filling out this issue form:** Ensure you have downloaded and are using the latest modpack version. 
  - type: textarea
    id: description
    attributes:
      label: ##Describe the bug
      description: A clear and concise description of what the bug is and affects.
      placeholder: My friend flipped upside down and, when walking forward, started zooming into the sky at the speed of sound.
    value: "Description"
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: "**Steps to reproduce**"
      description: "Steps to reproduce the behaviour:"
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. Scroll down to ...
        4. See error
      value: "Steps to Reproduce"
      validations:
        required: false
  - type: input
    id: version
    attributes:
      label: "**Server Version**"
      description: "The current version of the server (the version number from the latest changelog, i.e. v1.8)"
      placeholder: "vX.Y.Z"
      value: "Server Version"
    validations:
      required: true
  - type: input
    id: expected
    attributes:
      label: "**Expected Behaviour"
      description: "A clear and concise desription of what you expected to happen."
      vlue: "Expected Bahaviour"
    validations:
      required: false
  - type: input
    id: screenshots
    attributes:
      label: "**Screenshots (Optional)**"
      description: "If applicable, add screenshots to help explain the problem."
      value: "None"
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: "**Additional Context**"
      description: "Added notes or context surrounding the issue."
      value: "None"
    validations:
      required: false
